/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as NewRouteImport } from './routes/new'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ReferralsRouteImport } from './routes/referrals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/arrival' | '/insights' | '/new' | '/referral' | '/referrals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arrival' | '/insights' | '/new' | '/referral' | '/referrals'
  id:
    | '__root__'
    | '/'
    | '/arrival'
    | '/insights'
    | '/new'
    | '/referral'
    | '/referrals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrivalRoute: typeof ArrivalRoute
  InsightsRoute: typeof InsightsRoute
  NewRoute: typeof NewRoute
  ReferralRoute: typeof ReferralRoute
  ReferralsRoute: typeof ReferralsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrivalRoute: ArrivalRoute,
  InsightsRoute: InsightsRoute,
  NewRoute: NewRoute,
  ReferralRoute: ReferralRoute,
  ReferralsRoute: ReferralsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
