/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrivalRouteImport } from './routes/arrival'
import { Route as BasicPhoneRouteImport } from './routes/basic-phone'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as NewRouteImport } from './routes/new'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as ApiPublicVoiceRouteImport } from './routes/api/public/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalRoute = ArrivalRouteImport.update({
  id: '/arrival',
  path: '/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicPhoneRoute = BasicPhoneRouteImport.update({
  id: '/basic-phone',
  path: '/basic-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceRoute = ApiPublicVoiceRouteImport.update({
  id: '/api/public/voice',
  path: '/api/public/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/basic-phone': typeof BasicPhoneRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/print': typeof PrintRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/sync': typeof SyncRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/basic-phone': typeof BasicPhoneRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/print': typeof PrintRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/sync': typeof SyncRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrival': typeof ArrivalRoute
  '/basic-phone': typeof BasicPhoneRoute
  '/insights': typeof InsightsRoute
  '/new': typeof NewRoute
  '/print': typeof PrintRoute
  '/referral': typeof ReferralRoute
  '/referrals': typeof ReferralsRoute
  '/sync': typeof SyncRoute
  '/api/public/voice': typeof ApiPublicVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrival'
    | '/basic-phone'
    | '/insights'
    | '/new'
    | '/print'
    | '/referral'
    | '/referrals'
    | '/sync'
    | '/api/public/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrival'
    | '/basic-phone'
    | '/insights'
    | '/new'
    | '/print'
    | '/referral'
    | '/referrals'
    | '/sync'
    | '/api/public/voice'
  id:
    | '__root__'
    | '/'
    | '/arrival'
    | '/basic-phone'
    | '/insights'
    | '/new'
    | '/print'
    | '/referral'
    | '/referrals'
    | '/sync'
    | '/api/public/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrivalRoute: typeof ArrivalRoute
  BasicPhoneRoute: typeof BasicPhoneRoute
  InsightsRoute: typeof InsightsRoute
  NewRoute: typeof NewRoute
  PrintRoute: typeof PrintRoute
  ReferralRoute: typeof ReferralRoute
  ReferralsRoute: typeof ReferralsRoute
  SyncRoute: typeof SyncRoute
  ApiPublicVoiceRoute: typeof ApiPublicVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival': {
      id: '/arrival'
      path: '/arrival'
      fullPath: '/arrival'
      preLoaderRoute: typeof ArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-phone': {
      id: '/basic-phone'
      path: '/basic-phone'
      fullPath: '/basic-phone'
      preLoaderRoute: typeof BasicPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice': {
      id: '/api/public/voice'
      path: '/api/public/voice'
      fullPath: '/api/public/voice'
      preLoaderRoute: typeof ApiPublicVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrivalRoute: ArrivalRoute,
  BasicPhoneRoute: BasicPhoneRoute,
  InsightsRoute: InsightsRoute,
  NewRoute: NewRoute,
  PrintRoute: PrintRoute,
  ReferralRoute: ReferralRoute,
  ReferralsRoute: ReferralsRoute,
  SyncRoute: SyncRoute,
  ApiPublicVoiceRoute: ApiPublicVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
